// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName
import { application } from "./application"

import ClipboardController from "./clipboard_controller.js"
application.register("clipboard", ClipboardController)

import DropzoneController from "./dropzone_controller.js"
application.register("dropzone", DropzoneController)

import MapsController from "./maps_controller.js"
application.register("maps", MapsController)

import MyPostsController from "./my_posts_controller.js"
application.register("my-posts", MyPostsController)

import SearchPostsController from "./search_posts_controller.js"
application.register("search-posts", SearchPostsController)

import RadioSelectionController from './radio_selection_controller';
application.register('radio-selection', RadioSelectionController);
