// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClipboardController from "./clipboard_controller.js"
application.register("clipboard", ClipboardController)

import ConfirmEmailController from "./confirm_email_controller.js"
application.register("confirm-email", ConfirmEmailController)

import DatetimeController from "./datetime_controller.js"
application.register("datetime", DatetimeController)

import DelayRedirectController from "./delay_redirect_controller.js"
application.register("delay-redirect", DelayRedirectController)

import DetailLengthController from "./detail_length_controller.js"
application.register("detail-length", DetailLengthController)

import DropzoneController from "./dropzone_controller.js"
application.register("dropzone", DropzoneController)

import FileImageController from "./file_image_controller.js"
application.register("file-image", FileImageController)

import ForgotPasswordController from "./forgot_password_controller.js"
application.register("forgot-password", ForgotPasswordController)

import LiveValidateController from "./live_validate_controller.js"
application.register("live-validate", LiveValidateController)

import MapsController from "./maps_controller.js"
application.register("maps", MapsController)

import MyPostsController from "./my_posts_controller.js"
application.register("my-posts", MyPostsController)

import PasswordToggleController from "./password_toggle_controller.js"
application.register("password-toggle", PasswordToggleController)

import PostImageController from "./post_image_controller.js"
application.register("post-image", PostImageController)

import PostPreviewController from "./post_preview_controller.js"
application.register("post-preview", PostPreviewController)

import RadioSelectionController from "./radio_selection_controller.js"
application.register("radio-selection", RadioSelectionController)

import ResetPasswordController from "./reset_password_controller.js"
application.register("reset-password", ResetPasswordController)

import SearchFormController from "./search_form_controller.js"
application.register("search-form", SearchFormController)

import SearchPostsController from "./search_posts_controller.js"
application.register("search-posts", SearchPostsController)

import ShowMapController from "./show_map_controller.js"
application.register("show-map", ShowMapController)

import RemoveImageController from "./remove_image_controller.js"
application.register("remove-image", RemoveImageController)
