# Ruby
# Package your Ruby application.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger: none

pool: ruby-rbenv
variables:
  RAILS_ENV: 'test'
  RUBY_VERSION: '3.1.2'

steps:
- script: |
    rbenv install ${RUBY_VERSION} --skip-existing
    rbenv rehash
    rbenv global $(RUBY_VERSION)
    gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: 'ruby initial setup'

- script: bundle exec rubocop --format junit -o TEST-rubocop.xml
  displayName: 'run exec rubocop with junit format'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '$(System.DefaultWorkingDirectory)/TEST-rubocop.xml'
    testRunTitle: 'Ruby tests'

- script: bundle exec rubocop --format html -o rubocop.html
  displayName: 'run exec rubocop with html format'

- task: PublishHtmlReport@1
  displayName: 'Publish HTML Report'
  condition: succeededOrFailed()
  inputs:
    reportDir: '$(System.DefaultWorkingDirectory)/rubocop.html'
