# Ruby
# Package your Ruby application.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger: none

pool: ruby-rbenv
variables:
  RUBY_VERSION: '3.1.2'

steps:
- script: |
    rbenv install ${RUBY_VERSION} --skip-existing
    rbenv rehash
    rbenv global $(RUBY_VERSION)
    gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: 'Bundle install'

- script: yarn install
  displayName: 'Run yarn install'

- script: yarn lint
  displayName: 'Run yarn lint'

- script: yarn scss:lint
  displayName: 'Run yarn scss:lint'