default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lost_item_development

test:
  <<: *default
  database: lost_item_test

production:
  <<: *default
  database: lost_item_production
